variables:
  SCRIPT: '"%CI_PROJECT_DIR%\.gitlab-ci.bat" "C:\UE\Engine\" "%CI_PROJECT_DIR%\"'

stages:
  - assemble
  - test
  - build
  - cook
  - package

# assemble

assemble:
  stage: assemble
  script: [ call %SCRIPT% Assemble ]
  artifacts:
    untracked: true

# test

test:
  stage: test
  dependencies: [ assemble ]
  only: [ develop-vlad ]
  script: [ call %SCRIPT% Test ]

# build

build_client_development_win64:
  stage: build
  dependencies: [ assemble ]
  script: [ call %SCRIPT% Build Client Development Win64 ]
  artifacts:
    untracked: true

build_client_shipping_win64:
  stage: build
  dependencies: [ assemble ]
  script: [ call %SCRIPT% Build Client Shipping Win64 ]
  artifacts:
    untracked: true

# cook

cook_client_development_win64:
  stage: cook
  dependencies: [ build_client_development_win64 ]
  script: [ call %SCRIPT% Cook Client Development Win64 ]
  artifacts:
    untracked: true

cook_client_shipping_win64:
  stage: cook
  dependencies: [ build_client_shipping_win64 ]
  script: [ call %SCRIPT% Cook Client Shipping Win64 ]
  artifacts:
    untracked: true
    
# package

package_client_development_win64:
  stage: package
  dependencies: [ cook_client_development_win64 ]
  script: [ call %SCRIPT% Package Client Development Win64 ]

package_client_shipping_win64:
  stage: package
  dependencies: [ cook_client_shipping_win64 ]
  script: [ call %SCRIPT% Package Client Shipping Win64 ]