variables:
  GIT_STRATEGY: none        # we disable fetch, clone or checkout for every job
  GIT_CHECKOUT: "false"     # as we only want to checkout and fetch in the preperation stage

stages:
  - fetch
  - generate
  - source
  - content

# stages:
#   - preperations
#   - compile
#   - build
#   - cook
#   - package

fetch:
  stage: fetch
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "true"
  script:
    - call C:\BuildScripts\StartBuild.bat

generate:
  stage: generate
  script:
    - call C:\BuildScripts\CompileScripts.bat

source:
  stage: source
  script:
    - "c:\ue\ue_4.25\Engine\Binaries\DotNET\UnrealBuildTool.exe" OpenTournamentEditor Development Win64 -project="%CI_PROJECT_DIR%/OpenTournament.uproject" -rocket -progress -noubtmakefiles -NoHotReloadFromIDE

#content:
#  stage: content
#  script: 
#    - call C:\BuildScripts\CookProject.bat

# package:
#   stage: package
#   only:
#     - web                 # only archive when started through the web interface
#     - schedules           # only archive when started at a specific schedule
#   script:
#     - echo "Adding build to the artifacts"
#     - call C:\BuildScripts\Archive.bat
#   artifacts:
#     paths:
#       - PROJECT_NAME.zip
#     expire_in: 5 days
