variables:
  GIT_STRATEGY: none
  GIT_CHECKOUT: "false"
  BRANCH_DEVELOPMENT: 'development-placeholder'
  BRANCH_TESTING: 'testing'
  BRANCH_STAGING: 'staging'
  BRANCH_PRODUCTION: 'production'
  SCRIPT: '"$CI_PROJECT_DIR\Automation\Windows\Scripts\Automation.bat" "C:\UE\Engine\" "$CI_PROJECT_DIR\"'

stages:
  - validate
  - build
  - stage
  - archive

# TO-DO
#
# validate
#   structure
#   source
#   content
# build
#   compile
#     config #1
#     config #2
#     etc.
#   cook
#     config #1
#     config #2
#     etc.
# stage
#   move
#     config #1
#     config #2
#     etc.
#   inject
#     config #1
#     config #2
#     etc.
# package
#   archive
#     config #1
#     config #2
#     etc.
#   upload
#     config #1
#     config #2
#     etc.

# --------------------------------------------------
#     Validate
# --------------------------------------------------

validate 1/3:
  stage: validate
  script: [ call %SCRIPT% Assemble ]
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "true"

validate_A 2/3:
  stage: validate
  script: [ call %SCRIPT% Assemble ]
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "true"

validate_B 3/3:
  stage: validate
  script: [ call %SCRIPT% Assemble ]
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "true"

# --------------------------------------------------
#     Validate
# --------------------------------------------------

# This stage will make sure the project's structure, source and content are without obvious warnings and errors.

# --------------------------------------------------
#     Build
# --------------------------------------------------

build_client_development_win64:
  stage: build
  script: [ call %SCRIPT% Build Client Development Win64 ]
  only:
    variables:
      - $CI_PIPELINE_SOURCE == "schedule"

#build_client_shipping_win64:
#  stage: build
#  script: [ call %SCRIPT% Build Client Shipping Win64 ]
#  only:
#    variables:
      - $CI_PIPELINE_SOURCE == "schedule"

# --------------------------------------------------
#     Cook
# --------------------------------------------------

#cook_client_development_win64:
#  stage: cook
#  script: [ call %SCRIPT% Cook Client Development Win64 ]
#  only:
#    variables:
#      - $CI_PIPELINE_SOURCE == "schedule"

#cook_client_shipping_win64:
#  stage: cook
#  script: [ call %SCRIPT% Cook Client Shipping Win64 ]
#  only:
#    variables:
#      - $CI_PIPELINE_SOURCE == "schedule"

# --------------------------------------------------
#     Stage
# --------------------------------------------------

stage_client_development_win64:
  stage: stage
  script: [ call %SCRIPT% Stage Client Development Win64 ]
  only:
    variables:
      - $CI_PIPELINE_SOURCE == "schedule"

#stage_client_shipping_win64:
#  stage: stage
#  script: [ call %SCRIPT% Stage Client Shipping Win64 ]
#  only:
#    variables:
#      - $CI_PIPELINE_SOURCE == "schedule"

# --------------------------------------------------
#     Package
# --------------------------------------------------

archive_client_development_win64:
  stage: archive
  script: [ call %SCRIPT% Archive Client Development Win64 ]
  artifacts:
    paths: [ '%CI_PROJECT_DIR%\Output\Archived\Client\Development\Win64' ]
    expire_in: 1 week
  only:
    variables:
      - $CI_PIPELINE_SOURCE == "schedule"

#archive_server_development_win64:
#  stage: archive
#  script: [ call %SCRIPT% Archive Client Development Win64 ]
#  artifacts:
#    paths: [ '%CI_PROJECT_DIR%\Output\Archived\Client\Development\Win64' ]
#    expire_in: 1 week
#  only:
#    variables:
#      - $CI_PIPELINE_SOURCE == "schedule"
