variables:
  GIT_STRATEGY: none
  GIT_CHECKOUT: "false"
  SCRIPT: '"%CI_PROJECT_DIR%\.gitlab-ci.bat" "C:\UE\Engine\" "%CI_PROJECT_DIR%\"'

stages:
  - assemble
  - build
  - cook
  - stage
  - archive

# --------------------------------------------------
#     Assemble
# --------------------------------------------------

assemble:
  stage: assemble
  script: [ call %SCRIPT% Assemble ]
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "true"

# --------------------------------------------------
#     Build
# --------------------------------------------------

build_client_development_win64:
  stage: build
  script: [ call %SCRIPT% Build Client Development Win64 ]

build_client_shipping_win64:
  stage: build
  script: [ call %SCRIPT% Build Client Shipping Win64 ]

# --------------------------------------------------
#     Cook
# --------------------------------------------------

cook_client_development_win64:
  stage: cook
  script: [ call %SCRIPT% Cook Client Development Win64 ]

cook_client_shipping_win64:
  stage: cook
  script: [ call %SCRIPT% Cook Client Shipping Win64 ]

# --------------------------------------------------
#     Stage
# --------------------------------------------------

stage_client_development_win64:
  stage: stage
  script: [ call %SCRIPT% Package Client Development Win64 ]

stage_client_shipping_win64:
  stage: stage
  script: [ call %SCRIPT% Package Client Shipping Win64 ]

# --------------------------------------------------
#     Archive
# --------------------------------------------------

# This phase will be handled in the near future.