variables:
  automation-tool: '"C:/Program Files/Epic Games/UE_4.25.1/Engine/Binaries/DotNET/AutomationTool.exe"'
  unreal-build-tool: '"C:/Program Files/Epic Games/UE_4.25.1/Engine/Binaries/DotNET/UnrealBuildTool.exe"'
  unreal-editor: '"C:/Program Files/Epic Games/UE_4.25.1/Engine/Binaries/Win64/UE4Editor-Cmd.exe"'
  project-path: '"D:/Professional/Projects/DevOpsTests/DevOpsTests.uproject"'
  project-name: 'DevOpsTests'

stages:
  - assembly
  - editor-development-win64
  - client-development-win64
  - client-development-linux
  - client-shipping-win64
  - client-shipping-linux
  - server-development-win64
  - server-development-linux
  - server-shipping-win64
  - server-shipping-linux

# assembly

fetch:
  stage: assembly
  script:
    - call C:\BuildScripts\StartBuild.bat

generate:
  stage: assembly
  script:
    - call C:\BuildScripts\CompileScripts.bat

# editor-development-win64

source:
  stage: editor-development-win64
  only:
    - develop-vlad
  script:
    - call {{$unreal-build-tool}} OpenTournamentEditor Development Win64 -project="%CI_PROJECT_DIR%/OpenTournament.uproject" -rocket -progress -noubtmakefiles -NoHotReloadFromIDE

#content:
#  stage: editor-development-win64
#  only:
#    branch: [develop-vlad]
#    schedule: [cron * * * * *] 
#  script:

# client-development-win64

# client-development-linux

# client-shipping-win64

# client-shipping-linux

# server-development-win64

# server-development-linux

# server-shipping-win64

# server-shipping-linux
