variables:
  # This is the name of your ".uproject" file.
  TITLE: 'OpenTournament'
  # These folders represent the setup of the machine which reads this automation file.
  ROOT_TOOLS: 'C:\UE\Engine\Binaries'
  ROOT_PROJECT: '%CI_PROJECT_DIR%'
  # These paths are extensions of the root paths.
  PATH_AUTOMATION_TOOL: '%ROOT_TOOLS%\Build\BatchFiles\RunUAT.bat'
  PATH_UNREAL_BUILD_TOOL: '%ROOT_TOOLS%\Binaries\DotNET\UnrealBuildTool.exe'
  PATH_UNREAL_EDITOR: '%ROOT_TOOLS%\Binaries\Win64\UE4Editor-Cmd.exe'
  PATH_PROJECT: '%ROOT_PROJECT%\%TITLE%.uproject'
  # These parameters are overwritten by individual jobs.
  EXECUTABLE_TYPE: ''
  EXECUTABLE_CONFIGURATION: ''
  EXECUTABLE_PLATFORM: ''
  # These commands represent the various phases of the packaging process.
  COMMAND_BUILD: '%PATH_AUTOMATION_TOOL% BuildTarget -Project=%PATH_PROJECT% -Target=%TITLE% -NoTools'
  COMMAND_COOK: '%PATH_AUTOMATION_TOOL% BuildCookRun -Project=%PATH_PROJECT% -Target=%TITLE%%EXECUTABLE_TYPE% -Platform=%EXECUTABLE_PLATFORM% -Cook -SkipEditorContent -Compressed -Unversioned'
  COMMAND_STAGE: '%PATH_AUTOMATION_TOOL% BuildCookRun -Project=%PATH_PROJECT% -Target=%TITLE%%EXECUTABLE_TYPE% -Platform=%EXECUTABLE_PLATFORM% -Stage -SkipCook'

stages:
  - assembly
  - editor-development-win64-source
  - editor-development-win64-content
  - client-development-win64
  - client-development-linux
  - client-shipping-win64
  - client-shipping-linux
  - server-development-win64
  - server-development-linux
  - server-shipping-win64
  - server-shipping-linux

# assembly

assembly:
  stage: assembly
  script:
    - call %PATH_UNREAL_BUILD_TOOL% %CI_PROJECT_DIR%\%TITLE%.uproject -ProjectFiles -Game -Progress

# editor-development-win64

editor-development-win64-source:
  stage: editor-development-win64-source
  only:
    - develop-vlad
  variables:
    EXECUTABLE_TYPE: 'Editor'
    EXECUTABLE_CONFIGURATION: 'Development'
    EXECUTABLE_PLATFORM: 'Win64'
  script:
    - call %COMMAND_BUILD%

editor-development-win64-content:
  stage: editor-development-win64-content
  only:
    - develop-vlad
  variables:
    EXECUTABLE_TYPE: 'Editor'
    EXECUTABLE_CONFIGURATION: 'Development'
    EXECUTABLE_PLATFORM: 'Win64'
  script:
    - call %COMMAND_BUILD%

#content:
#  stage: editor-development-win64
#  only:
#    branch: [develop-vlad]
#    schedule: [cron * * * * *] 
#  script:

# client-development-win64

# client-development-linux

# client-shipping-win64

# client-shipping-linux

# server-development-win64

# server-development-linux

# server-shipping-win64

# server-shipping-linux