variables:
  BATCH: '%CI_PROJECT_DIR%\.gitlab-ci.bat "C:\UE\Engine\"'

stages:
  - assemble
  - test
  - build
  - cook
  - package
#  - editor-development-win64
#  - client-development-win64
#  - client-development-linux
#  - client-shipping-win64
#  - client-shipping-linux
#  - server-development-win64
#  - server-development-linux
#  - server-shipping-win64
#  - server-shipping-linux

# assemble

assemble:
  stage: assemble
  script:
    start "%CI_PROJECT_DIR%\.gitlab-ci.bat "C:\UE\Engine\" Assemble"

# build

build_client_development_win64:
  stage: build
  script:
    start "%CI_PROJECT_DIR%\.gitlab-ci.bat "C:\UE\Engine\" Build Client Development Win64"

build_client_shipping_win64:
  stage: build
  script:
    start "%CI_PROJECT_DIR%\.gitlab-ci.bat "C:\UE\Engine\" Build Client Shipping Win64"

# cook

#cook_client_development_win64:
#  stage: cook
#  script:
#    call %CI_PROJECT_DIR%\.gitlab-ci.bat "C:\UE\Engine\" Cook Client Development Win64
#    needs build_client_development_win64
#
#cook_client_shipping_win64:
#  stage: cook
#  script:
#    call %CI_PROJECT_DIR%\.gitlab-ci.bat "C:\UE\Engine\" Cook Client Shipping Win64
#    needs build_client_shipping_win64
#
## package
#
#package_client_development_win64:
#  stage: package
#  script:
#    call %CI_PROJECT_DIR%\.gitlab-ci.bat "C:\UE\Engine\" Package Client Development Win64
#    needs cook_client_development_win64
#
#package_client_shipping_win64:
#  stage: package
#  script:
#    call %CI_PROJECT_DIR%\.gitlab-ci.bat "C:\UE\Engine\" Package Client Shipping Win64
#    needs cook_client_shipping_win64
#

    
# editor-development-win64

#editor-development-win64:
#  stage: editor-development-win64
#  only:
#    - develop-vlad
#  script:
#    - call %ROOT_PROJECT%\.gitlab-ci.bat %ROOT_TOOLS% "%ROOT_PROJECT%/" Test