variables:
  SCRIPT: '"%CI_PROJECT_DIR%\.gitlab-ci.bat" "C:\UE\Engine\" "%CI_PROJECT_DIR%\"'

stages:
  - assemble
  - test
  - build
  - cook
  - package

# assemble

assemble:
  stage: assemble
  script:
    call %SCRIPT% Assemble

# test

test:
  stage: test
  only: [ develop-vlad ]
  script:
    call %SCRIPT% Test
    needs assemble
    artifact true

# build

build_client_development_win64:
  stage: build
  script:
    call %SCRIPT% Build Client Development Win64
    needs assemble
    artifact true

build_client_shipping_win64:
  stage: build
  script:
    call %SCRIPT% Build Client Shipping Win64
    needs assemble
    artifact true

# cook

cook_client_development_win64:
  stage: cook
  script:
    call %SCRIPT% Cook Client Development Win64
    needs build_client_development_win64
    artifact true

cook_client_shipping_win64:
  stage: cook
  script:
    call %SCRIPT% Cook Client Shipping Win64
    needs build_client_shipping_win64
    artifact true

# package

package_client_development_win64:
  stage: package
  script:
    call %SCRIPT% Package Client Development Win64
    needs cook_client_development_win64
    artifact true

package_client_shipping_win64:
  stage: package
  script:
    call %SCRIPT% Package Client Shipping Win64
    needs cook_client_shipping_win64
    artifact true