variables:
  GIT_STRATEGY: none
  GIT_CHECKOUT: "false"
  SCRIPT: '"%CI_PROJECT_DIR%\.gitlab-ci.bat" "C:\UE\Engine\" "%CI_PROJECT_DIR%\"'

stages:
  - assemble
  - build
  - cook
  - stage
  - archive

# --------------------------------------------------
#     Assemble
# --------------------------------------------------

assemble:
  stage: assemble
  script: [ call %SCRIPT% Assemble ]
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "true"

# --------------------------------------------------
#     Build
# --------------------------------------------------

build_client_development_win64:
  stage: build
  script: [ call %SCRIPT% Build Client Development Win64 ]
  only: [ testing ]

build_client_shipping_win64:
  stage: build
  script: [ call %SCRIPT% Build Client Shipping Win64 ]
  only: [ testing ]

# --------------------------------------------------
#     Cook
# --------------------------------------------------

cook_client_development_win64:
  stage: cook
  script: [ call %SCRIPT% Cook Client Development Win64 ]
  only: [ testing ]

cook_client_shipping_win64:
  stage: cook
  script: [ call %SCRIPT% Cook Client Shipping Win64 ]
  only: [ testing ]

# --------------------------------------------------
#     Stage
# --------------------------------------------------

stage_client_development_win64:
  stage: stage
  script: [ call %SCRIPT% Stage Client Development Win64 ]
  only: [ testing ]

stage_client_shipping_win64:
  stage: stage
  script: [ call %SCRIPT% Stage Client Shipping Win64 ]
  only: [ testing ]

# --------------------------------------------------
#     Archive
# --------------------------------------------------

archive_client_development_win64:
  stage: archive
  script: [ call %SCRIPT% Archive Client Development Win64 ]
  only: [ testing ]
  artifacts:
    paths: [ '%CI_PROJECT_DIR%\Output\Archived\Client\Development\Win64' ]
    expire_in: 1 week

archive_client_shipping_win64:
  stage: archive
  script: [ call %SCRIPT% Archive Client Shipping Win64 ]
  only: [ testing ]
  artifacts:
    paths: [ '%CI_PROJECT_DIR%\Output\Archived\Client\Shipping\Win64' ]
    expire_in: 1 week