variables:
  GIT_STRATEGY: none
  GIT_CHECKOUT: "false"
  SCRIPT: '"%CI_PROJECT_DIR%\.gitlab-ci.bat" "C:\UE\Engine\" "%CI_PROJECT_DIR%\"'

stages:
  - time
  - run-child-1
  - run-child-2
  
time:
  script:
    - time
run-child-1:
  trigger:
    include: child-1.yml
run-child-2:
  trigger:
    include: child-2.yml

#stages:
#  - assemble
#  - test
#  - build
#  - cook
#  - package
#
## assemble
#
#assemble:
#  stage: assemble
#  variables:
#    GIT_STRATEGY: fetch
#    GIT_CHECKOUT: "true"
#  script: [ call %SCRIPT% Assemble, trigger .gitlab-client-development-win64.yml ]
## test
#
#test:
#  stage: test
#  only: [ develop-vlad ]
#  script: [ call %SCRIPT% Test ]

# build

#build_client_development_win64:
#  stage: build
#  script: [ call %SCRIPT% Build Client Development Win64 ]
#
#build_client_shipping_win64:
#  stage: build
#  script: [ call %SCRIPT% Build Client Shipping Win64 ]
#
## cook
#
#cook_client_development_win64:
#  stage: cook
#  script: [ call %SCRIPT% Cook Client Development Win64 ]
#
#cook_client_shipping_win64:
#  stage: cook
#  script: [ call %SCRIPT% Cook Client Shipping Win64 ]
#
## package
#
#package_client_development_win64:
#  stage: package
#  script: [ call %SCRIPT% Package Client Development Win64 ]
#
#package_client_shipping_win64:
#  stage: package
#  script: [ call %SCRIPT% Package Client Shipping Win64 ]