variables:
  GIT_STRATEGY: none        # we disable fetch, clone or checkout for every job
  GIT_CHECKOUT: "false"     # as we only want to checkout and fetch in the preperation stage

stages:
  - assembly
  - editor-development-win64
  - client-development-win64
  - client-development-linux
  - client-shipping-win64
  - client-shipping-linux
  - server-development-win64
  - server-development-linux
  - server-shipping-win64
  - server-shipping-linux

# assembly

fetch:
  stage: assembly
  script:
    - call C:\BuildScripts\StartBuild.bat

generate:
  stage: assembly
  script:
    - call C:\BuildScripts\CompileScripts.bat

# editor-development-win64

source:
  stage: editor-development-win64
  only:
    branch: [develop-vlad]
    schedule: [cron * * * * *] 
  script:
    - call "C:\UE\Engine\Binaries\DotNET\UnrealBuildTool.exe" OpenTournamentEditor Development Win64 -project="%CI_PROJECT_DIR%/OpenTournament.uproject" -rocket -progress -noubtmakefiles -NoHotReloadFromIDE

#content:
#  stage: editor-development-win64
#  only:
#    branch: [develop-vlad]
#    schedule: [cron * * * * *] 
#  script:

# client-development-win64

# client-development-linux

# client-shipping-win64

# client-shipping-linux

# server-development-win64

# server-development-linux

# server-shipping-win64

# server-shipping-linux
